// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdZUSZ83LdPxr-D7r6RT0jqY6EsU2Ud6Q',
    appId: '1:1080641144589:web:17a185ed55640e64e95244',
    messagingSenderId: '1080641144589',
    projectId: 'dytest1-c7a86',
    authDomain: 'dytest1-c7a86.firebaseapp.com',
    databaseURL: 'https://dytest1-c7a86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dytest1-c7a86.appspot.com',
    measurementId: 'G-GRF21E3BLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7Hw2aYh4DC60yJJ5VB4ROYTvcavWjCs',
    appId: '1:1080641144589:android:02906cabd9074330e95244',
    messagingSenderId: '1080641144589',
    projectId: 'dytest1-c7a86',
    databaseURL: 'https://dytest1-c7a86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dytest1-c7a86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0U2V5oGXC6U-Gh2Y3ECA07e16zXCZlt0',
    appId: '1:1080641144589:ios:e03a65d49111f301e95244',
    messagingSenderId: '1080641144589',
    projectId: 'dytest1-c7a86',
    databaseURL: 'https://dytest1-c7a86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dytest1-c7a86.appspot.com',
    iosBundleId: 'com.example.dyt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0U2V5oGXC6U-Gh2Y3ECA07e16zXCZlt0',
    appId: '1:1080641144589:ios:339fbd3428058989e95244',
    messagingSenderId: '1080641144589',
    projectId: 'dytest1-c7a86',
    databaseURL: 'https://dytest1-c7a86-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dytest1-c7a86.appspot.com',
    iosBundleId: 'com.example.dyt.RunnerTests',
  );
}
